export const data = [
    { 
      id: '1', 
      orderNumber: { en: 'DP78890', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 1, 2017', ar: '١ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Shipping', ar: 'شحن' }, 
      itemsPurchased: { en: '2', ar: '٢' }, 
      image: require("./Images/shoe1.png"),
    },
    { 
      id: '2', 
      orderNumber: { en: 'DP78081', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 1, 2017', ar: '١ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Shipping', ar: 'شحن' }, 
      itemsPurchased: { en: '1', ar: '١' }, 
      image: require("./Images/shoe1.png"), 
    },
    { 
      id: '3', 
      orderNumber: { en: 'DP79082', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 2, 2017', ar: '٢ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Delivered', ar: 'تم التوصيل' }, 
      itemsPurchased: { en: '3', ar: '٣' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '4', 
      orderNumber: { en: 'DP79183', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 3, 2017', ar: '٣ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Pending', ar: 'قيد الانتظار' }, 
      itemsPurchased: { en: '1', ar: '١' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '5', 
      orderNumber: { en: 'DP79284', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 4, 2017', ar: '٤ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Delivered', ar: 'تم التوصيل' }, 
      itemsPurchased: { en: '2', ar: '٢' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '6', 
      orderNumber: { en: 'DP79385', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 5, 2017', ar: '٥ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Shipping', ar: 'شحن' }, 
      itemsPurchased: { en: '1', ar: '١' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '7', 
      orderNumber: { en: 'DP79486', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 6, 2017', ar: '٦ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Delivered', ar: 'تم التوصيل' }, 
      itemsPurchased: { en: '3', ar: '٣' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '8', 
      orderNumber: { en: 'DP79587', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 7, 2017', ar: '٧ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Pending', ar: 'قيد الانتظار' }, 
      itemsPurchased: { en: '2', ar: '٢' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '9', 
      orderNumber: { en: 'DP79688', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 8, 2017', ar: '٨ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Shipping', ar: 'شحن' }, 
      itemsPurchased: { en: '1', ar: '١' }, 
      image: require("./Images/shoe1.png"),  
    },
    { 
      id: '10', 
      orderNumber: { en: 'DP79789', ar: '١٠١٢٣٤' }, 
      orderDate: { en: 'August 9, 2017', ar: '٩ أغسطس ٢٠١٧' }, 
      orderStatus: { en: 'Delivered', ar: 'تم التوصيل' }, 
      itemsPurchased: { en: '2', ar: '٢' }, 
      image: require("./Images/shoe1.png"),  
    },
  ];
  